kblincoe/elasticsearch

- Coordination.md
Request to add 22768: Evil_Engineers to Coordination.md
> Request to update Coordination.md

- Coordination.md
Sorry for misspelling my group name
23208: java ych not jch
> Update Coordination.md misspelling my group name

- Coordination.md
> Claimed issue 23044

- Coordination.md
Added our next issue that we are planning to work on;
15965: Misleading error message for geo_point parse failure
> Added JTeam1 proposed issues

- Coordination.md
> Claim issue 21946

- Coordination.md
Claiming issues 16641 and 23268.
> Update issues 16641 and 23268

- Coordination.md
Reason: Seems issue 15965 has been fixed in the master, but not updated in the issue list (No pull requests were mentioned). We were unable to reproduce the issue in the master branch.
> Changing our issue to 21862

- Coordination.md
> update issue 11310

- Coordination.md
> Claimed the issue 23436

- Coordination.md
> Update Coordination.md claiming issue 11295

- Coordination.md
> Claim Issue 14114

- Coordination.md
> Claim issue 23646

- Coordination.md
> Changed from issue 18109 to 21978

- Coordination.md
> Unclaimed 23646

- Coordination.md
> Update Coordination.md claim 23646

- Coordination.md
> Update Coordination.md claiming issue 21312

- Coordination.md
> Update Coordination.md claiming issue 8217

- Coordination.md
> Update Coordination.md to claim #8362

- Coordination.md
Add issues 23231 to group Random 2
> Update Coordination.md for group Random 2 (issue 23231)

- Coordination.md
> Claimed Issue 23131

- Coordination.md
> Update Coordination.md to claim #10795

- Coordination.md
Removed the issue 16564 because our team already completed two issues.
> Removed issue 16564

- Coordination.md
Now working on issue 9373 instead of 23131
> Changed issue claim for Random 2

- Coordination.md
> Group LT would like to claim #23720

- Coordination.md
> Group LT would like to claim #23699

- Coordination.md
> Claim issue #3590 and release issue #10795

- plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
- plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java
- plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3OutputStream.java
- plugins/repository-s3/src/test/java/org/elasticsearch/cloud/aws/blobstore/S3BlobStoreContainerTests.java
ignoring the retry method at S3Output
> maintaining retries from s3 blob store and ignoring the retry method at S3Output. Close 22845

- core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java
- core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java
- core/src/test/java/org/elasticsearch/search/builder/SearchSourceBuilderTests.java
Unhandled query size parameter is fixed, if size and from < 0 , throw new IllegalArgumentException. Also the corresponded test is added and some changes of word phrase.
> Fixed Issue 22530 : Unhandled query size parameter

- core/src/main/java/org/elasticsearch/index/analysis/StandardHtmlStripAnalyzer.java
remove StandardHtmlStripAnalyzer()
> remove standardhtmlanalyzer. close issue 4704

- core/src/main/java/org/elasticsearch/index/similarity/SimilarityService.java
Remove classic similarity from defaults.
> Remove classic similarity from defaults. close 23208

- core/src/test/java/org/elasticsearch/search/aggregations/bucket/HistogramIT.java
**Changes**
- A test was added to make sure `histogram` aggregation intervals with an input of `1d` would work as intended. 
- Another test that checks that an interval of `null` is not accepted and an exception is thrown as there is no default interval. 
- One further test was added that checks that the number of Docs cannot be less than 0 for a `histogram` aggregation.
**Notes on issue 23193**
After looking at the issue it seemed that elastic search was working as intended for the example given. As the histogram wasn't a `date_histogram` aggregation, `1d` was parsed into a double with the value of 1, similarly, it seems that the date values `indexed("2017-02-15T17:39:00.000Z", "2017-02-15T17:40:00.000Z")` were converted into UNIX time(in terms of ms) hence the histogram being created …
> Added test cases to histogram Aggregations. Closes issue 23193. 

- core/src/main/java/org/elasticsearch/script/ScriptService.java
This pull request addresses issue 12315. 
Currently, the search template render API would return a 500 status code on malformed template which is a result of the GeneralScriptException. I have changed it to return a 400 status code i.e. ElasticsearchParseException to better reflect the malformed template error.
> Changed returned status code for malformed templates to 400 from 500

- core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
Specifying an invalid date format as an array is allowed in ElasticSearch. Instead of throwing an error  later when executing the mapping actions, additional date format validation has been added to capture this error when creating indices.
> Closed issue 23650. Added date field validation when creating indicies

- docs/reference/index-modules.asciidoc
> Add description of how to apply best_compression

- modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
Changed regexes to fit valid UTF-8 values.
An exception is now shown to the user when invalid UTF-8 is entered.
Invalid UTF-8 encoded strings were accepted by Elasticsearch when they were not meant to be, possibly causing errors for the user when decoding later.
To fix the issue, a checking system was added to check the request content is within the UTF-8 encoding range. If the request is not in the range then the program throws an exception.
> Fix issue #9538 - Added UTF8 text checking for request content

- Coordination.md
- core/src/main/java/org/elasticsearch/common/lucene/search/MoreLikeThisQuery.java
For issue #23720 we have added an if statement before currenFieldName is set, in order to check if the entry is correct and would not cause an error later on. If it is incorrect, a helpful error message will appear explaining what the problem is.
For issue #23699 we were unable to fully solve the issue but we located the document and commented what we think might be wrong. No changes to the code were made because we cannot be sure to not break the code.
We also experienced many problems running gradle on the lab computers which made it hard to run elasticsearch and test effectively, however we eventually got gradle and elasticsearch working on our personal laptops but still had some issues with testing.
> Fix issue #23720 and issue #23699

- core/src/main/java/org/elasticsearch/rest/action/RestActions.java
- core/src/main/java/org/elasticsearch/rest/action/document/RestDeleteAction.java
> Throw Exception when DELETE Request contains body

- docs/reference/mapping/types/geo-shape.asciidoc
Fixed issue 3590 by adding a note in the documentation to specify the coordinate system used.
> #3590 Documentation now states coordinates format

- core/src/main/java/org/elasticsearch/search/fetch/subphase/FetchSourceContext.java
When do source filtering names, there was inconsistency in the query parameters vs request body.
Ticket 22792
Expected behavior is: 
executing the request and the deprecation coming back as a header.
> Ticket #22792, fixed inconsistency between query parameters vs request body

- core/src/test/java/org/elasticsearch/common/io/stream/BytesStreamsTests.java
Test had @ignore annotation, now it's removed.
> 12620 - removed unused test
