core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java, core/src/test/java/org/elasticsearch/common/joda/DateMathParserTests.java
When a non-UTC timestamp was parsed to an epoch format, it would fail with the error message, **"failed to parse date field [1484334000000] with format [epoch_millis]"** This was incorrect as it was not a parse failure but an issue with non-UTC time zones being incompatible with the epoch format. 
The new error message reflects this
=> Improved error message parsing a non UTC date to epoch

core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestClearIndicesCacheAction.java, core/src/test/java/org/elasticsearch/rest/action/admin/indices/RestClearIndicesCacheActionTests.java, docs/reference/modules/indices/request_cache.asciidoc, rest-api-spec/src/main/resources/rest-api-spec/api/indices.clear_cache.json, rest-api-spec/src/main/resources/rest-api-spec/test/indices.clear_cache/10_basic.yaml
(Issue 22748)
As per the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-clearcache.html), `request` is supposed to be the parameter that determines whether or not to clear the request cache when making a `_cache/clear` request, but this was not the case in the code (which used `request_cache`). 
This commit deprecates `request_cache` and introduces `request` as the parameter that should be used.
=> Deprecate request_cache for clearing an index's cache.

docs/reference/mapping/types/keyword.asciidoc
`search_analyzer` is not actually supported on keyword field. Updating the docs
for now to remove `search_analyzer` since it currently does not work
Closes Issue 23609
=> Remove `search_analyzer` parameter on 'keyword field' documentation (23609)

core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java
Added a regex expression to determine if a port range is specified in the config file, "elasiticsearch.yml" in the "config" folder of the built application. If this is the case an exception will be thrown as this is unsupported.
example: Contents of  elasiticsearch.yml
```
.... 
discovery.zen.ping.unicast.hosts : ["128.0.0.1", "127.0.0.1:9000", "192.0.0.1:9200-9300"]
....
```
In this example the third entry "192.0.0.1:9200-9300" will cause the exception to be thrown.
upi: msyk659     group: Group 1
=> Fix Issue 15816 Add exception if port range specified for discovery.zen.ping.unicast.hosts 

core/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateEmptyPrimaryAllocationCommand.java, core/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateStalePrimaryAllocationCommand.java
WARN level messages will be logged when a user changes the routing of primary shards. This is used to inform them what actions have been executed that can lead to data loss.
=> Closes issue 22821, Added WARN level logging messages when reallocating primary shards

core/src/main/java/org/elasticsearch/action/DocWriteResponse.java, core/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexResponse.java, core/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java, core/src/main/java/org/elasticsearch/action/index/IndexResponse.java
@kblincoe 
Important: Issue 23044 "returns index input" is not addressed due to an existing pull request/code for the issue. Instead the JSON request data is returned to the terminal for user confirmation.
**For example the command,**
```json
curl -XPUT 'http://localhost:9200/kimchy/tweet/1?pretty' -H 'Content-Type: application/json' -d '
{
"user": "kimchy",
"post_date": "2009-11-15T13:12:00",
"message": "Trying out Elasticsearch, so far so good?"
}'
```
**now returns,**
```json
{
"_index" : "kimchy",
"_type" : "tweet",
"_id" : "1",
"_version" : 1,
"result" : "created",
"_request" : "{    user: kimchy,    post_date: 2009-11-15T13:12:00,    message: Trying out Elasticsearch, so far so good?}",
"_shards" : {
"total" : 2,
"successful" : 1,
"failed" : 0
},
"_seq_no" : 0,
"created" : true
} …
```
=> Returns index input on create index request (23044)

docs/plugins/analysis-icu.asciidoc, plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuCollationTokenFilterFactory.java, plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuFoldingTokenFilterFactory.java, plugins/analysis-icu/src/test/java/org/elasticsearch/index/analysis/SimpleIcuCollationTokenFilterTests.java
Parameters in IcuFoldingTokenFilterFactory and IcuCollatedTokenFilterFactory have been modified to use snake case instead of camel case. Tests and documents were also changed to reflect these changes.
=> Renamed ICU token filters parameters to snake case (22823)

docs/reference/indices/update-settings.asciidoc
Elasticsearch 5.x now offers the ability to reset Index settings by submitting a `null` value for the indices. 
This behavior is now documented in the Update Settings Doc. For any users that are not in the latest version of Elasticsearch a link is provided showing how to upgrade Elasticsearch depending on which version the user is currently on. An example is shown in the documentation.
=> Fix issue 22870: Documenting the ability to reset index settings with null values in Update Indices Settings doc

core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java, core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java
Range queries that have both bounds open are costly to execute. The rewrite phase of queries
provides the opportunity to rewrite queries as faster running simpler queries. This PR switches to
an `exists` query if both bounds are open.
The output should be the same for both queries below, but under the hood an exists query is ultimately used
```java
// typical query
GET _search
{
"query" : {
"range" : {
"post_date" : { "from" : "2009-11-15T13:00:00", "to" : "2009-11-15T14:00:00" }
}
}
}'
```
```java
// open bounds query
GET _search
{
"query" : {
"range" : {
"post_date" : { }
}
}
}'
```
Closes issue 22640
=> Rewrite `range` to `exists` query when bounds are open (22640)

docs/plugins/repository-s3.asciidoc
The documentation has been updated to complete issue 23435.
This update was completed by adding the statement that if the base path starts with "/", that ability has been deprecated.
=> Updated document to complete 23435

core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java
Histogram Aggregation API returns keys with insignificant digits, this is fixed by overloading the round function.
=> Closes issue 23664, Added a function to round floating key values when calling histogram aggregation function

core/src/main/java/org/elasticsearch/cli/ExitCodes.java, core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java
The current build has a number of generic exit codes that do not give much information. This pull request adds a unique exit code for failure of plugin installation (if a user is attempting to install a currently installed plugin).
=> Create new exit code for issue 15295

core/build/resources/test/org/elasticsearch/action/search/simple-msearch5.json, core/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java, core/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java
Adds a check that any multisearch request has the appropriate trailing marker for that content type.
Adds a unit test to ensure an exception is thrown if the expected marker is missing.
Resolves 7601.
7601 identifies that the example request fails if there is no trailing newline, however checking for a trailing newline causes tests to fail.  Reading the code, I am fairly certain that the inconsistency they were experiencing was due to a lack of a trailing marker, which was a newline in their case.
@kblincoe 
@Helen-Zhao
@azho472
=> Add check for trailing marker in Msearch requests

Coordination.md, client/client-benchmark-noop-api-plugin/src/main/java/org/elasticsearch/plugin/noop/action/bulk/RestNoopBulkAction.java, client/rest-high-level/src/main/java/org/elasticsearch/client/Request.java, client/rest-high-level/src/test/java/org/elasticsearch/client/RequestTests.java, core/src/main/java/org/elasticsearch/action/bulk/byscroll/AbstractAsyncBulkByScrollAction.java, core/src/main/java/org/elasticsearch/action/bulk/byscroll/AbstractBulkByScrollRequest.java, core/src/main/java/org/elasticsearch/action/bulk/byscroll/AbstractBulkByScrollRequestBuilder.java, core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestRolloverIndexAction.java, core/src/main/java/org/elasticsearch/rest/action/document/RestBulkAction.java, core/src/main/java/org/elasticsearch/rest/action/document/RestDeleteAction.java, core/src/main/java/org/elasticsearch/rest/action/document/RestIndexAction.java, core/src/main/java/org/elasticsearch/rest/action/document/RestUpdateAction.java, docs/reference/docs/index_.asciidoc, docs/reference/docs/reindex.asciidoc, modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBaseReindexRestHandler.java, modules/reindex/src/test/java/org/elasticsearch/index/reindex/RoundTripTests.java, modules/reindex/src/test/resources/rest-api-spec/test/delete_by_query/50_wait_for_active_shards.yaml, modules/reindex/src/test/resources/rest-api-spec/test/reindex/60_wait_for_active_shards.yaml, modules/reindex/src/test/resources/rest-api-spec/test/update_by_query/50_consistency.yaml, rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json, rest-api-spec/src/main/resources/rest-api-spec/api/reindex.json, rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json, test/framework/src/main/java/org/elasticsearch/action/bulk/byscroll/AbstractBulkByScrollRequestTestCase.java
- Change `timeout` param to `shard_timeout` for the following APIs: `reindex`, `update_by_query` and `delete_by_query`
- Update references of the param throughout code and test cases to use the new param `shard_timeout`
Resolves issue 17620
=> Rename timeout param for reindex, update_by_query and delete_by_query rest APIs

core/src/main/java/org/elasticsearch/common/lucene/search/MoreLikeThisQuery.java, core/src/main/java/org/elasticsearch/common/lucene/search/XMoreLikeThis.java, core/src/main/java/org/elasticsearch/index/query/MoreLikeThisQueryBuilder.java
Closes issue 14114.
Changes made:
- Added maxDocFreqPct field in appropriate classes (MoreLikeThis.java, MoreLikeThisQueryBuilder.java)
- Set default value for MAX_DOC_FREQ_PCT to 100. 
- Added max doc freq pct in appropriate methods (hashcode(), equals(), etc)
Commits were peer reviewed [here.](https://github.com/bawse/elasticsearch/commit/209acead74e696b7b68185aec8251f2da25093ad)
Note:
Since this change required the addition of a field and updating method invocations, some (around 6) tests were failed - not because of error in the code but due to the fact that the tests were not aware of this additional field (maxDocFreqPct). Changes to the tests were not very easy to make.
=> Add Max Doc Frequency Percentage in MoreLikeThis query

core/src/main/java/org/elasticsearch/rest/action/document/RestUpdateAction.java
Fixes 16671.
Added a check that throws an error if the request has both upsert and a version.
=> Reject request with both upsert and a version

core/src/main/java/org/elasticsearch/action/termvectors/TermVectorsResponse.java, core/src/test/java/org/elasticsearch/action/termvectors/TermVectorsUnitTests.java
Added sourceAsMap() and sourceAsString() to TermVectorsResponse. These
methods provide extra utility for converting term vectors to a Map or
String format.
=> Fix #10441

core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java
When performing a RangeQuery with dates using an epoch string. Values near Long.MAX_VALUE will cause returned results to be incorrect. 
Example Query:
```
{
"query": {
"range": {
"test_date": {
"from": null,
"to": 9223372036854775807,
"include_lower": true,
"include_upper": true
}
}
}
}
```
Caused by parseDateTime in DateMathParser:
- Parser adds 23:59:59:999 (hh:mm:ss:mil) to dates without times based on roundUpIfNoTime boolean input. This boolean input is based off the include_upper/include_lower in the query which is valid except in the case of an epoch string. If input epoch value is within the 24h window, the parser will return an overflowed value (near Long.MIN_VALUE).
- Default parse format is "strict_date_optional_time||epoch_millis". It is unknown what format the input is until …
=> Fix issue 23436: RangeQuery values near Long.MAX_VALUE incorrectly processed

core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java, core/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java, core/src/test/java/org/elasticsearch/index/mapper/DocumentMapperParserTests.java
**Changes:**
Check the length of the string array returned after splitting `fullFieldPath` (path provided by the user). The splitting is done to interpret the path from the field name as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html). The array will not contain any element if the splitting was unsuccessful resulting in an `ArrayIndexOutOfBounds` exception. 
**Why:**
Rather than complaining the user about an `ArrayIndexOutOfBounds` exception, now it provides a clear message that the provided field name is invalid.
_Fixes the issue 21862_
=> Fix 21862 : Improve the validation check for the field name and its mapping 

core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java
Fixes issue 8362 by logging the number of candidates that were expected when said number is not met.
=> 8362: Log number of required candidates on failure

core/src/main/java/org/elasticsearch/action/admin/indices/alias/get/GetAliasesRequest.java, rest-api-spec/src/main/resources/rest-api-spec/api/cat.aliases.json
Updated the GetAliasesRequest constructor (in GetAliasesRequest.java) to properly handle multiple aliases.
Also updated [cat.aliases.json](https://github.com/elastic/elasticsearch/blob/6265ef1c1ba1d308bcc28d00dccccac555e33b89/rest-api-spec/src/main/resources/rest-api-spec/api/cat.aliases.json#L9-L12) to document {name} as a string of comma-separated alias names instead of a list.
Closes issue 23661.
=> Bug fix for cat aliases not returning any records when querying with multiple alias names

core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java, core/src/test/java/org/elasticsearch/node/internal/InternalSettingsPreparerTests.java
Fixes "Fail hard if .yml exists in 5.0.0" in issue 19391.
Changes made:
- .yml removed from list of allowed suffixes in ES5.0
- Updated exception error message so that it now notifies users that .yml is no longer supported. (only .yaml and .json are)
- updated test class with aforementioned error message
=> Fail hard if .yml exists in 5.0.0

docs/reference/indices/update-settings.asciidoc
A new parameter, 'preserveExisting' ,was added earlier to preserve existing settings when doing setting update. If the parameter is set to true, existing settings on an index remain unchanged. The default value of the parameter is false.
This was not documented and this pull request documents the above mentioned functionality.
=> Closed Issue 23673, Documented preserveExisting parameter setting

core/src/main/java/org/elasticsearch/action/search/SearchRequest.java, core/src/test/java/org/elasticsearch/search/scroll/SearchScrollIT.java
A scroll query search does not make sense if the size specified and returned is 0. Thus a validation exception should be thrown when the size is 0.
A test case for when the size is 0 is included. A test for valid input is NOT included as it is redundant. The other test cases in the test suite already tests for valid scroll queries multiple times.
Have run "gradle check" with no problems.
- Added new ValidationException for when a scroll query has a size of 0
- Included new test case to check if exception is thrown correctly
Closes issue 22552
=> Added validation exception for when a scroll search returns a size of 0.

core/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsRequest.java
Closes issue 10096.
This change exposes the `CommonStatsFlags` property in `IndicesStatsRequest` in a similar fashion as `NodesStatsRequest`. 3 overloaded methods added allow access to the stats flags, toggling on/off all stats, and specifying which stats should be displayed.
=> Move IndicesStatsRequest to expose CommonStatsFlags directly (Closes 10096)

core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/RangeAggregationBuilderTest.java
Added a test case for 22881. However, due to certain issues in how the context works and difficulty in replication, the context variable has been kept null. Once that is determined and the dependent pr (23241) merged, the test case will pass.
=> Partial addition of test case for 22881

core/src/main/java/org/elasticsearch/repositories/Repository.java, core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java, core/src/main/java/org/elasticsearch/rest/action/cat/RestSnapshotAction.java, core/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java, core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java, core/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java, core/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
Closes issue 18543.
Currently, snapshots do not have a field describing the size of the snapshot itself. The inclusion of the size would be used to determine whether there is enough disk space on the target cluster before the execution of a restore. The changes include calculating the current size of the Shards in the Snapshot.
- Included the size of the snapshot by adding appropriate fields and a constructor to the `SnapshotInfo` class. 
- A method to calculate this size (in bytes) was also added.
- A parameter containing the list of `ShardIds` were added to the `finalizeSnapshot` method in order to calculate the size.
=> Snapshot size added to snapshot metadata 

core/src/test/java/org/elasticsearch/search/aggregations/bucket/DateRangeIT.java, core/src/test/java/org/elasticsearch/search/aggregations/bucket/IpRangeIT.java, core/src/test/java/org/elasticsearch/search/aggregations/bucket/RangeIT.java, docs/reference/aggregations/bucket/range-aggregation.asciidoc
**Changes**
- Integration Tests were added to ensure the `missing` option works correctly with `range`, `date_range`, and `ip_range` aggregations.
- Changes were made to to the `range-aggregation.asciidoc` documentation to mention that the `missing` option is supported for these aggregations.
**Notes on Issue 17597**
- The existing integration tests had some minor differences in naming and patterns (e.g. different methods used to setting up the indices, `assertThat` vs. `assertEquals`, etc.) ,  between `RangeIT.java`, `DateRangeIT.java`, and `IpRangeIT.java`. I tried to follow the schemes of each file to remain consistent with what was already there to maintain readability.
- Overall the `missing` option seems to work fine for these range aggregations, and this change should ensure that …
=> Add Integration Test for missing option in range, date_range, and ip_range aggregations. Resolve 17597.

core/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java, core/src/main/java/org/elasticsearch/indices/analysis/PreBuiltTokenFilters.java, core/src/test/java/org/elasticsearch/action/termvectors/GetTermVectorsIT.java, core/src/test/java/org/elasticsearch/script/IndexLookupIT.java, docs/reference/analysis/tokenfilters/delimited-payload-tokenfilter.asciidoc, test/framework/src/main/java/org/elasticsearch/AnalysisFactoryTestCase.java
Changed delimited_payload_filter to delimited_payload in all occurrences in the elasticsearch project.
(The issue said delimiter_payload_filter however the occurrences in the project were called delimited_payload_filter, so was spelt incorrectly in issue)
The changes were done in four classes and six test cases.
No comments were written as they were unnecessary.
=> Fix issue #21978 - Delimiter_payload

core/src/main/java/org/elasticsearch/rest/RestRequest.java
Invalid queries that end with a "%" symbol such as http://localhost9200/?% (query part: /?%), threw out an exception to the server 
and did not give a formatted message to the client. Fix has been implemented so that a formatted error message will be sent to the client.
The fix was implemented an if-else statement that swapped any "%" symbol that is found at the end of a query 
to "%25" (the correct encoding for "%" symbol). The modified query is then passed back to Elasticsearch which carries on with the usual functionality
=> Fix issue #21974 - Added fix for percentage encoding issue

Coordination.md, client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java, client/rest/src/test/java/org/elasticsearch/client/RestClientBuilderTests.java
I changed the setting for the RestClient from defualt to the  JVM system defaults for SSL . This helps on reindex as it uses the RestClient internally and can be easily configured to trust different certificates.
Sourcecode changed in method **createHttpClient()** of the file **RestClientBuilder.java** . I use useSysstemProerties() at the end to overwrite the defaults setting. More detailed documentation is [here](https://hc.apache.org/httpcomponents-asyncclient-dev/httpasyncclient/apidocs/org/apache/http/impl/nio/client/HttpAsyncClientBuilder.html). 
I wrote a unit test to test if the client is set up according to system properties in class **TestClientBuilder.java**. I set the system properties wrongly on purpose, and test if the Client is built wrongly. If the Client is using the …
=> Fix issue #23231

core/src/main/java/org/elasticsearch/index/VersionType.java
This pull requests closes issue 21278.
The change fixes a problem where version number is -1, the error message was not very informative (it should indicate that a file is not found). The error message now contains informative text when required.
_Changes:_
-Updated text in errors related to incorrect version - now indicates that the document was not found
-Updated text in errors related to incorrect version - now indicates that the document was not found only when version is -1, rather than all the time
-Updated VersionType.java to have line widths of less than 140
=> Updated text in errors related to incorrect version: #21278

core/src/main/java/org/elasticsearch/common/xcontent/AbstractObjectParser.java, core/src/main/java/org/elasticsearch/common/xcontent/ObjectParser.java, core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java, core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightBuilder.java, docs/reference/search/request/highlighting.asciidoc
This pull request contains following changes:
1. Functionality changes: Fix issue 21802
Description: By modifying logics in ObjectParser class, now String value "true"|"false" in highlight searching can be accepted, and it will not trigger an illegal argument exception.
File involved: core/org/elasticsearch/common/xcontent/ObjectParser.java,                             core/org/elasticsearch/common/xcontent/AbstractObjectParser.java.
2. Code Comments for issue 21802
Description: Add comments for the part of code which has been modified, together with some descriptions of mechanisms of highlight searching function, which may helpful for future contributors.
File involved: core/org/elasticsearch/common/xcontent/ObjectParser.java
core/org/elasticsearch/search/fetch/subphase/highlight/Abstract …
=> Fixing Issue# 21802: 'require_field_match' parameter should accept "true"|"false"

docs/reference/mapping.asciidoc
Added information about what a mapping explosion is and why its bad to the documentation.
=> updated the documentation to reflect what mapping explosions are - 23687

core/src/main/java/org/elasticsearch/common/settings/loader/JsonSettingsLoader.java, core/src/main/java/org/elasticsearch/common/xcontent/XContentFactory.java, core/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContent.java, core/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContentGenerator.java, core/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContentParser.java
This PR fixes the second sub-issue in issue 19391 : "deprecate support for .json in 2.4.0"
JSON is deprecated for ES 2.4.0 as support for it will be removed in ES 5.0
YAML should be used in its place.
Changes: 
- Added Deprecation annotation to relevant classes and methods involving JSON content type
- Added JavaDoc documentation to explain why something is deprecated
=> Deprecate support for .json in 2.4.0

core/src/main/java/org/elasticsearch/action/admin/indices/get/GetIndexRequest.java
- added if statement to check the request body is empty or not
- created content for empty body exception 
([The Issue link is here](https://github.com/elastic/elasticsearch/issues/17853))
Before this update
Sending an empty body results a wrong / confused exception
After update
The exception can response that the empty body is not allowed.
=> Fix issue #17853 - POST index/_settings with body produces wrong exception

core/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java
Will coerce document properties defined as a number to a string when using Simulate Pipeline API.
Does this by converting value parsed from JSON document definition to String if it is of type Integer.
Will only convert if type is Integer (preventing invalid types parsed from JSON document definition)
Value extracted from configuration map is of type object, so javadocs updated to reflect the types that object is allowed to be 
May cause merge conflicts with other pull requests fixing issues with 'ingest' label as similar files are likely to have been modified. Take care when attempting to merge into master.
=> Fix 23823 Coerce Ingest Simulate document properties to string

core/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java, docs/reference/ingest/ingest-node.asciidoc
Will deliver a more useful error message to user when using they specify
a short form script (not allowed) with the Pipeline Simulate API.
No commenting necessary for this pull request
Documentation file updated
May cause conflicts with the changes made in pull request 172 or any pull requests
attempting to fix issue 23823 as similar files are being modified. 
May also cause merge conflicts with pull requests fixing issues with 'ingest' label as similar files are likely to have been modified. Again take care when attempting to merge into master.
=> Fix 23824 Handle ingest inline scripts more appropriately
